/*
    CSC236 8N0 Intro to C#
    Project: Final Project
    File: Program.cs
    By: Len Mahaffey
    Last Edited: 12/11/20
    Description: auto generated by Visual Studio
*/
using System;
using System.Windows.Forms;

namespace CSC236_LMahaffey_FinalProject
{
    static class Program
    {
        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new MainForm());
        }
    }
}
